const jwt = require("jsonwebtoken");
const { db } = require("../auth/firebaseConfig");

// Set default JWT secret for development
if (!process.env.JWT_SECRET) {
  process.env.JWT_SECRET = "development-jwt-secret-key";
}

const verifyAuth = async (req, res, next) => {
  try {
    const authHeader = req.headers.authorization;
    if (!authHeader || !authHeader.startsWith("Bearer ")) {
      return res.status(401).json({
        error: "Unauthorized",
        message: "Authorization header is required"
      });
    }

    const token = authHeader.split("Bearer ")[1];
    let decodedToken;

    try {
      // Verify the JWT token generated by auth.js
      decodedToken = jwt.verify(token, process.env.JWT_SECRET);
    } catch (jwtError) {
      return res.status(401).json({
        error: "Unauthorized",
        message: "Invalid or expired token"
      });
    }

    // Get user data from Firestore using the UID from the decoded JWT
    const userDoc = await db.collection("users").doc(decodedToken.uid).get();
    const userData = userDoc.data();
    
    if (!userDoc.exists || !userData.isActive) {
      return res.status(401).json({
        error: "Unauthorized",
        message: "User not found or account is inactive"
      });
    }

    req.user = { ...decodedToken, role: userData.role };
    next();
  } catch (error) {
    console.error("Authentication verification error:", error);
    return res.status(500).json({
      error: "Internal server error",
      message: error.message
    });
  }
};

module.exports = verifyAuth;


